### ISSUE TITLE
Handover of the model

### ISSUE THREAD

**Issue by colidyre** [exc-asia-and-europe/ecpo-segment#14]
The trained model is to be handed over. This can be done in a similar way to Issue #13 .

**Comment by Simon-Will** [comment]
@duncdrum, the trained model is 127 MiB large. Do you want me to commit it to this repo?

**Comment by duncdrum** [comment]
That would require `git-lfs` so you'd need to add info about it being required to the readme. But yes, it strikes me as the cleanest approach.

**Comment by Simon-Will** [comment]
In commit ce5a26c, the `all-detection-1` model is added via Git LFS and installation information is added to the README. I’m closing this issue.
