### ISSUE TITLE
How to get annotations for one image?

### ISSUE THREAD

**Issue by Simon-Will** [exc-asia-and-europe/ecpo-segment#2]
One image (e.g. double page) has several annotations. But the API endpoint `annotations` does not list all annotations for one image contiguously. This means that there is no way to know when all annotations for one image have been downloaded before all annotations for all images are downloaded. By extension, this means all of the annotations have to be held in memory (or stored on disk) before any of the masks can be written, which is impossible or at least tedious.

How can one get the annotations for only one image or at least request annotations for only a subset of images? E.g. for all Jingbao images from April 1921.

**Comment by Simon-Will** [comment]
@duncdrum, I know you didn’t write the API, but maybe you can refer the author to this issue.

**Comment by duncdrum** [comment]
not the final answer but here is a link to the code repo https://gitlab.existsolutions.com/foss/web-annotation-protocol

**Comment by Simon-Will** [comment]
I am still waiting for an answer here. The [web annotation protocol readme](https://gitlab.existsolutions.com/foss/web-annotation-protocol/blob/master/README.md) says that the document (the fold in our case) can be specified via the `document-id` query parameter,  but it also says that this feature is not yet implemented.

I don’t know much about Xquery, but the [annotations.xqm](https://gitlab.existsolutions.com/foss/web-annotation-protocol/blob/master/modules/annotations.xqm) has a function `annotations:handle-list` that passes on the `document` query parameter to `annotations:list`, which in turn expects the parameter `document-id`. This might be a bug.

Also, I don’t know how to get hold of the document ids (which I assume are the ids in the target objects) efficiently.

**Comment by Simon-Will** [comment]
@line-no, can you give some information here?

**Comment by Simon-Will** [comment]
@line-o, can you give some information here?

**Comment by line-o** [comment]
@Simon-Will the readme is outdated, my bad. 
The query is `/exist/wap/annotations/?document=<document-url>`,
where **document-url** is the fully-qualified url of the image.
Example URL (the **target** element's **source** attribute value):
`https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1940/03/jb_4116_1940-03-31_0002%252B0003.tif/full/full/0/default.jpg`

**Comment by Simon-Will** [comment]
@line-o, thanks for the info! Now that that’s clear, I will close this issue.
