### ISSUE TITLE
Doubly-encoded query string in Source URL

### ISSUE THREAD

**Issue by Simon-Will** [exc-asia-and-europe/ecpo-segment#4]
When querying the annotations API, there is a source URL given. But the query string seems to be doubly url-encoded. E.g. a URL referring to a file called `1+2.jpg` will look like `https://example.com/?IIIF=1%252B2.jpg`, i.e. the `+` will be `%252B` instead of `%2B`.

This might be an error in the API, but I cannot find the relevant repository to put the issue there.

**Comment by duncdrum** [comment]
This is how the current IIIF image server is providing the URLs. We are in the process of setting up a new one, where this won't happen anymore. For actual production use, you ll have to mirror the messy urls for now.

The new server is WIP here https://github.com/JoeTo1/iipsrv-ecpo

**Comment by duncdrum** [comment]
@JoeTo1 please let us know in here if there is any relevant news about the new iiif server

**Comment by JoeTo1** [comment]
In my opinion we will not bugfix iipsrv. Instead we will stop using "+" in our URL logig.  This becomes a temporary issue.

See:
https://iipimage.sourceforge.io/documentation/protocol/

See discussion https://github.com/ruven/iipsrv/issues/44

For IIP FIF commands, just a single encoding with %2B is sufficient:

https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?FIF=%2FimageStorage%2Fecpo_new%2Fanhui_funu%2Fvolume001%2Fissue0002%2Fahfn_vol001_issue0002_0002%2B0003.tif&WID=500&CVT=JPEG

**Comment by Simon-Will** [comment]
I worked around this already anyway, so it is a non-issue for me at this point. I’m closing this.
